const prettier = require("prettier");
const fs = require("fs");
const path = require("path");
const pkg = require("../../package.json");

const schemaPath = path.join(process.cwd(), "src", "server", "database", "schema.d.ts");
const config = pkg.natuna["#database"];
let types = "";

switch (config.driver) {
    case "mysql":
    default:
        for (const [key, value] of Object.entries(config.schema)) {
            types += `${key}: {\n`;

            for (const [subKey, subValue] of Object.entries(value)) {
                types += `${subKey}: ${subValue};`;
            }

            types += `};`;
        }
}

const result = `
// This file is autogenerated, you should not edit it.
declare type DatabaseDriver = "${config.driver}";
declare type DatabaseSchema = {${types}};
`;

const formatted = prettier.format(result, {
    ...pkg.prettier,
    parser: "typescript",
});

fs.writeFileSync(schemaPath, formatted);
